
	<style type="text/css">
		
		#buttonRegister {
		    background-color: #4CAF50;
            border: none;
            color: white;
            padding: 15px 25px;
            text-align: center;
            font-size: 16px;
            cursor: pointer;
            margin-left: 4px;
            margin-top: 50px;
            margin-bottom: 25px;
		}
		


	</style>

	<div style="background-color: gold;width:500px;margin-left: 250px; ">
		
		
            <center><h3>Registration Form </h3><center>
 
            <table border='0' width='280px' cellpadding='0' cellspacing='0' align='center'>
                <tr>
                    <td align='center'>FirstName:</td>
                    <td><input type="text" name="txtFirstName"></td>
                </tr>
                
                <tr>
                    <td align='center'>LastName:</td>
                    <td><input type="text" name="txtLAaName"></td>
                </tr>
                
                <tr>
                    <td align='center'>Email:</td>
                    <td> <input type="text" name="txtEmail"></td>
                </tr>
                
                <tr>
                    <td align='center'>Password:</td>
                    <td><input type="password" name="txtPassword"></td>
                </tr>
                
                <tr>
                    <td align='center'>Confirm Password :</td>
                    <td><input type="password" name="txtConfirmPwd"></td>
                </tr>

            </table>
       
 
		<div>
			<button type="button" id ="buttonRegister" onclick="location.href='index';">Register</button>
		</div>
	</div>
