      
    <div style="background-color: #E6E6FA;">
        <div class="fontclass">
            <marquee  direction="right">
            <?php
            echo $block->helloWorld()."<br><br>";?>
            </marquee>
        </div>

        <div style="color:green; margin:10px 10px 50px 500px; font-size: 16px;" >            
           <?php echo "Date  : " . date('d/m/Y')."<br>";?> </div>

        <div>
	        <img class="display" src="<?php echo $this->getViewFileUrl("Ceymox_Training::images/testimage.jpeg");?>" >
	    </div>
    </div>

    <div class="container">
        <div >
  	        <img src="<?php echo $this->getViewFileUrl("Ceymox_Training::images/az-large-5768052.jpg");?>" style="max-width:100%;
                     max-height:100%;margin-left: 80px; " >
	    </div>
        <div >
    	    <br/><br/><br/><br/>
            <a href="home" style="margin-left:60px;">CEYMOX TECHNOLOGIES</a>
        </div>
        <div >
    	<br/><br/><br/>
    	    <a href="home"style="margin-left:120px;">Home</a><br>
    	    <a href="home" style="margin-left:120px;">About Us</a><br>
    	    <a href="home" style="margin-left:120px;">Contact Us</a><br>
    	    <a href="register" style="margin-left:120px;">Register</a>
            
        </div>
    </div>




